### ISSUE TITLE
Hot reload doesn't work

### ISSUE THREAD

**Issue by denieler** [layershifter/react-source-render#10]
Hey, guys!

Thanks for the library, I've tried to use it, it's really cool. But found an issue there that `hot-reload` stopped working with using this package. I did a little investigation and it looks like a problem is in the `memoization`
here
https://github.com/layershifter/react-source-render/blob/master/src/createElementFromSource/transformSource.js#L31
and here
https://github.com/layershifter/react-source-render/blob/master/src/createElementFromSource/createComponentFromSource.js#L16

do you think it's possible to pass like a parameter or something into `SourceRender` component to disable memoization or force it to reset?
Thanks!

**Comment by layershifter** [comment]
Can you please make a minimal repro repo based on CRA? And provide some steps?

I've checked on:
```
"react": "^16.8.4",
"react-dom": "npm:@hot-loader/react-dom",
"react-hot-loader": "^4.8.0"
```

- I haven't any issues with resolved components i.e. passed via resolver
- Sometimes I had an issue with cached code, but I was not able to find the clear repro case as props passed by component were correct

**Comment by layershifter** [comment]
- memoize in `transformSource()` is needed to skip Babel transforms on the same code
- memoize in `createComponentFromSource()` allows to cache React.Element and keep `element.type()` otherwise React will remount component and break component's state

**Comment by denieler** [comment]
@layershifter exactly, in my case, I have a code, for example, for Button component (source code):

```
import React from 'react'
import Button from './Button'

const ButtonCode = () => (
  <div>
    <Button text='My Button' />
  </div>
)

export default ButtonCode
```

and I want to change the code of `./Button` the component itself and after hot reload happen I want to see the updated Button rendered with `react-source-render`, but it doesn't happen because the source code has not been changed itself.

**Comment by layershifter** [comment]
> and I want to change the code of `./Button` the component itself and after hot reload happen

Actually, this scenario works in my setup:
![works](https://user-images.githubusercontent.com/14183168/54125347-69b14680-440d-11e9-9d24-dc793b1d37de.gif)

What version of `react-source-render` are you using?

**Comment by denieler** [comment]
I use the latest `"react-source-render": "^2.0.0-beta.6"`. It's quite strange, because why it would re-render if the babelConfig has not changed and sourceCode neither. I can prepare an example, hopefully, it will help identify the issue :) thanks!

**Comment by layershifter** [comment]
> because why it would re-render if the babelConfig has not changed and sourceCode neither.

The code of `Button` component will be processed with `react-hot-loader/babel`, so `Button` will 🔥

**Comment by denieler** [comment]
Sorry, guys, don't close please this issue, it still exists, I will prepare the example :)

**Comment by layershifter** [comment]
NP, it will be great to fix it 👍

**Comment by layershifter** [comment]
@denieler hey, I met the same problem 👎 

I recently published `react-source-render@3.0.0-2`, there are some changes in API, but at least you can test it 🐱 React 16.8 is required.

```jsx
<SourceRender
  babelConfig={babelConfig} // as before
  source={currentCode} // source code as before
  renderHtml // as before, to get markup
  resolver={importResolver} // as before
  themeName={themeName} // prop that will be passed to a created component, you can skip
  wrap={(element) => <Provider>{element}</Provider>} // if you want to wrap with your Provider
  unstable_hot // enables HMR power
>
  {({ element, error, markup }) => <div>{element}</div>}
</SourceRender>
```

**Comment by denieler** [comment]
@layershifter hey :) thanks for the fix!

we've recently fixed it with the workaround:
```
<SourceRender
            babelConfig={{
              presets: ['es2015']
            }}
            render={...}
            resolver={resolver}
            source={this.avoidSourceCodeMemoization(sourceCode)}
          >
```
and 
```
avoidSourceCodeMemoization = (sourceCode: string) => {
    return `
      ${sourceCode}

      function resetCode() { ${Math.random()} }
    `
  }
```

**Comment by layershifter** [comment]
Actually, this update does quite similar thing, but it listens for HMR states 😼

**Comment by denieler** [comment]
@layershifter hey! finally could try `3.0.0-5`, looks like it works, thank you for the fix! Will keep you updated if we will find any issues ❤️

**Comment by layershifter** [comment]
Great, thank you for feedback ❤️
