### ISSUE TITLE
View source link is broken

### ISSUE THREAD

**Issue by levithomason** [layershifter/react-source-render#9]
The "View source" link is broken:

https://github.com/layershifter/react-source-render/blob/988f16cb74b93d3d597fe0bc28e6f02bf246b856/components/Sandbox.js#L108

This should be:
```diff
-href="https://github.com/layershifter/react-source-render/blob/master/docs/components/Sandbox" 
+href="https://github.com/layershifter/react-source-render/blob/master/components/Sandbox.js"
```

**Comment by layershifter** [comment]
Docs deployed with newest version, thank you 👍
